### ISSUE TITLE
Archive hash has changed for 1.1.0

### ISSUE THREAD

**Issue by ktosiek** [Garados007/elm-svg-parser#8]
I've got a following error when trying to build an existing project that depend on 1.1.0:

```
-- CORRUPT PACKAGE DATA --------------------------------------------------------
 /home/jenkins/jenkins-agent/workspace/.../frontend/elm.json
 
 I downloaded the source code for Garados007/elm-svg-parser 1.1.0 from:
 
     https://github.com/Garados007/elm-svg-parser/zipball/1.1.0/
 
 But it looks like the hash of the archive has changed since publication:
 
   Expected: 4ce4bbe7dd38c507758896f8b563c8ec4f555b33
     Actual: e877f72c927587c6c02d071c561189ce29c11545
 
 This usually means that the package author moved the version tag, so report it
 to them and see if that is the issue. Folks on Elm slack can probably help as
 well.
 ```
 
 It looks like the tag was moved ~2 hours ago.

**Comment by ktosiek** [comment]
I've upgraded to 1.1.1, which works.

**Comment by Garados007** [comment]
Thanks for noticing. I tried to do a version bump and somehow I moved the tag. I have seen this and retried `elm bump` and the version was moved (correctly) to 1.1.1.

**Comment by Garados007** [comment]
Hmm. I cannot find commit 4ce4bbe7dd38c507758896f8b563c8ec4f555b33 and move the tag 1.1.0 back to it. I will keep it as it is right now.
